### ISSUE TITLE
Php5.5 install apcu-5.1.8 failed

### ISSUE THREAD

**Issue by Wshuhao001** [krakjoe/apcu#231] opened 2017-02-23 04:33 UTC
Php5.5 install apcu-5.1.8 failed. I have installed Zend Opcache, but when I want to install apcu the error occurred,i need help.
```
[root@ott apcu-5.1.8]# make
/bin/sh /usr/local/apcu-5.1.8/libtool --mode=compile cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/local/apcu-5.1.8 -DPHP_ATOM_INC -I/usr/local/apcu-5.1.8/include -I/usr/local/apcu-5.1.8/main -I/usr/local/apcu-5.1.8 -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /usr/local/apcu-5.1.8/apc.c -o apc.lo 
 cc -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/local/apcu-5.1.8 -DPHP_ATOM_INC -I/usr/local/apcu-5.1.8/include -I/usr/local/apcu-5.1.8/main -I/usr/local/apcu-5.1.8 -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /usr/local/apcu-5.1.8/apc.c  -fPIC -DPIC -o .libs/apc.o
In file included from /usr/local/apcu-5.1.8/apc_sma.h:34,
                 from /usr/local/apcu-5.1.8/apc_pool.h:33,
                 from /usr/local/apcu-5.1.8/apc_cache.h:36,
                 from /usr/local/apcu-5.1.8/apc.c:35:
/usr/local/apcu-5.1.8/apc_sma_api.h:46: 错误：expected specifier-qualifier-list before ‘zend_long’
In file included from /usr/local/apcu-5.1.8/apc_pool.h:36,
                 from /usr/local/apcu-5.1.8/apc_cache.h:36,
                 from /usr/local/apcu-5.1.8/apc.c:35:
/usr/local/apcu-5.1.8/apc_pool_api.h:142: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
/usr/local/apcu-5.1.8/apc_pool_api.h:143: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
In file included from /usr/local/apcu-5.1.8/apc_cache.h:40,
                 from /usr/local/apcu-5.1.8/apc.c:35:
/usr/local/apcu-5.1.8/apc_cache_api.h:44: 错误：expected specifier-qualifier-list before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:53: 错误：expected specifier-qualifier-list before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:67: 错误：expected specifier-qualifier-list before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:82: 错误：expected specifier-qualifier-list before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:101: 错误：expected specifier-qualifier-list before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:139: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:140: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:141: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:142: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
/usr/local/apcu-5.1.8/apc_cache_api.h:216: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:223: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:230: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:236: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:245: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:250: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:272: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:290: 错误：expected declaration specifiers or ‘...’ before ‘zend_string’
/usr/local/apcu-5.1.8/apc_cache_api.h:390: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from /usr/local/apcu-5.1.8/apc_cache.h:40,
                 from /usr/local/apcu-5.1.8/apc.c:35:
/usr/local/apcu-5.1.8/apc_cache_api.h:390: 错误：expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from /usr/local/apcu-5.1.8/apc.c:36:
/usr/local/apcu-5.1.8/apc_globals.h:44: 错误：expected specifier-qualifier-list before ‘zend_long’
/usr/local/apcu-5.1.8/apc.c:41:31: 错误：zend_smart_str.h：没有那个文件或目录
/usr/local/apcu-5.1.8/apc.c: 在函数‘apc_flip_hash’中:
/usr/local/apcu-5.1.8/apc.c:336: 警告：传递‘zend_hash_get_current_data_ex’的第 2 个参数时在不兼容的指针类型间转换
/usr/local/php5/include/php/Zend/zend_hash.h:182: 附注：需要类型‘void **’，但实参的类型为‘struct Bucket **’
/usr/local/apcu-5.1.8/apc.c:336: 错误：提供给函数‘zend_hash_get_current_data_ex’的实参太少
/usr/local/apcu-5.1.8/apc.c:338:61: 错误：宏“zend_hash_update”需要 6 个参数，但只给出了 3 个
/usr/local/apcu-5.1.8/apc.c:338: 错误：‘zend_hash_update’未声明(在此函数内第一次使用)
/usr/local/apcu-5.1.8/apc.c:338: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/usr/local/apcu-5.1.8/apc.c:338: 错误：所在的函数内也只报告一次。)
/usr/local/apcu-5.1.8/apc.c:340:68: 错误：宏“zend_hash_index_update”需要 5 个参数，但只给出了 3 个
/usr/local/apcu-5.1.8/apc.c:340: 错误：‘zend_hash_index_update’未声明(在此函数内第一次使用)
/usr/local/apcu-5.1.8/apc.c:345: 警告：传递‘_zval_ptr_dtor’的第 1 个参数时在不兼容的指针类型间转换
/usr/local/php5/include/php/Zend/zend_variables.h:51: 附注：需要类型‘struct zval **’，但实参的类型为‘struct zval *’
make: *** [apc.lo] 错误 1
```

**Comment by johnpupu** [comment] 2017-02-25 16:13
APCu 5.x is for php 7.x
APCu 4.x is just for php 5.x

APCu 5 的 版本 ~~~ 是給 php7 以上用的 ~~~~
請裝 APCu 4 的 版本

**Comment by cmb69** [comment] 2017-08-08 15:13
@Wshuhao001 If the issue is solved for you, please close this ticket.

**Closed** 2017-08-08 15:30 UTC
