### ISSUE TITLE
Fault in php-fpm

### ISSUE THREAD

**Issue by RamboLau** [krakjoe/apcu#153] opened 2015-12-07 03:39 UTC
when use php-fpm and apcu in php7,;

error:

```bash
Dec  7 09:33:05 localhost kernel: php-fpm[16593]: segfault at 10 ip 00002b2bad61a3d8 sp 00007fff545682f0 error 4 in apcu.so[2b2bad60f000+13000]
```

php version
```bash
PHP 7.0.0 (cli) (built: Dec  3 2015 18:05:30) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

apc version

```bash
[root@localhost ~]# php --ri apc

apc

APC Compatibility: => Disabled
Version => 5.1.0
Build Date => Nov 20 2015 12:53:52
```

apcu version

```bash
[root@localhost ~]# php --ri apcu

apcu

APCu Support => Disabled
Version => 5.1.0
APCu Debugging => Disabled
MMAP Support => Enabled
MMAP File Mask => /tmp/apc.XXXXXX
Serialization Support => Disabled
Build Date => Nov 20 2015 12:53:52

Directive => Local Value => Master Value
apc.enabled => On => On
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.ttl => 0 => 0
apc.smart => 0 => 0
apc.mmap_file_mask => /tmp/apc.XXXXXX => /tmp/apc.XXXXXX
apc.enable_cli => Off => Off
apc.slam_defense => On => On
apc.preload_path => no value => no value
apc.coredump_unmap => Off => Off
apc.use_request_time => On => On
apc.serializer => php => php
apc.writable => /tmp => /tmp
```

**Comment by krakjoe** [comment] 2015-12-07 05:14
> APCu Support => Disabled

Looks like apcu is disabled by configuration.

I'm not able to reproduce whatever, so need more information. 

Please provide reproducing code.

**Comment by RamboLau** [comment] 2015-12-07 05:46
@krakjoe 

```bash
APCu Support => Disabled
```

because i not change in apcu.ini

```bash
apc.enable_cli=0
```

**Comment by krakjoe** [comment] 2015-12-07 05:48
Oh yeah, of course ... it's before 6am on a Monday morning ... so forgive me if I'm a bit slow ;)

**Comment by krakjoe** [comment] 2015-12-07 05:54
I just realized you are using 5.1.0, I assume that's from pecl ...

Could you pull from git master branch and recompile apcu, there are many fixes committed since then but I can't do a release until I've got apcu-bc in order, which should be today ...

**Comment by RamboLau** [comment] 2015-12-07 05:58
@krakjoe tks, I will try later.

**Closed** 2015-12-07 06:00 UTC
Labels: feedback
