### ISSUE TITLE
apc_clear_cache() gives warning on PHP 7

### ISSUE THREAD

**Issue by cvuorinen** [krakjoe/apcu#163] opened 2016-01-07 21:27 UTC
Seems like this old issue has somehow surfaced again on PHP 7 https://github.com/krakjoe/apcu/issues/48

When calling `apc_clear_cache()` without parameters gives a PHP warning.

Here is the expected result:

```
$ php -v
PHP 5.6.6 (cli) (built: Feb 19 2015 10:30:11) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
$ php -r "var_dump(apc_clear_cache());"
bool(true)
```

But this is what I get on PHP 7:
```
$ php -v
PHP 7.0.1-5+deb.sury.org~wily+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans
$ php -r "var_dump(apc_clear_cache());"
PHP Warning:  apc_clear_cache() expects exactly 1 parameter, 0 given in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. apc_clear_cache() Command line code:1

Warning: apc_clear_cache() expects exactly 1 parameter, 0 given in Command line code on line 1

Call Stack:
    0.0000     359344   1. {main}() Command line code:0
    0.0000     359344   2. apc_clear_cache() Command line code:1

Command line code:1:
NULL
```

**Comment by remicollet** [comment] 2016-01-08 06:09
I think this is a duplicate of https://github.com/krakjoe/apcu-bc/issues/10 which is fixed in apcu-bc 1.0.1.

Please update. 
Closing as this is not related to apcu.

**Closed by remicollet** 2016-01-08 06:09 UTC
