### ISSUE TITLE
Weird apcu_fetch behaviour

### ISSUE THREAD

**Issue by szaqal83** [krakjoe/apcu#168] opened 2016-01-27 14:16 UTC
When I fetch value by this key: "http://www.xyz.com:terms:last_changed" which stores this value: "0.42599700 1453902068" and store it in object property (array) like this:
```
$this->last_changed[] = array(
				// $apc_key = "http://www.xyz.com:terms:last_changed"
				'terms' => apcu_fetch($apc_key)
			);
```
then I check whole $this->last_changed prop by var_dump() and it shows:
```
array(1) {
  [0]=>
  array(1) {
    ["terms"]=>
    string(21) "0.38007800 1453903141"
  }
}
```
so fetched value is a string ("0.42599700 1453902068" - apc admin script apc.php shows the same) but when I var_dump() $this->last_changed some time later at the end of my script (by another object method) it shows that $this->last_changed has magically became something this:
```
array(1) {
  [0]=>
  array(1) {
    ["terms"]=>
    string(254) "O:8:"stdClass":10:{s:7:"term_id";i:528;s:4:"name";s:2:"AA";s:4:"slug";s:6:"fghfgh";s
:10:"term_group";i:0;s:16:"term_taxonomy_id";i:530;s:8:"taxonomy";s:13:"district_name";s:11:"description"
;s:0:"";s:6:"parent";i:0;s:5:"count";i:0;s:6:"filter";s:3:"raw";}"
  }
}
```
$this->last_changed is being set only in one place and I don't use any reference passing. Checking in apc.php admin script shows that stored value is still "0.38007800 1453903141".

my workaround for this by now is to force fetched result to string:

```
$this->last_changed[] = array(
				// $apc_key = "http://www.xyz.com:terms:last_changed"
				'terms' => apcu_fetch($apc_key) . '' // manual cast to string
			);
```
I'm not sure if it is a apcu_fetch bug or it's something else. This whole script is my object cache implementation for WordPress so there are other things involved in execution process but even digging inside core files of WP didn't gave me any clue what could be the reason of this behaviour.

This bug occuers on **PHP 7.0.2** and **APCu 5.1.3 (without Backward Compatibility extension)**, on **PHP 5.6.17** and **APCu 4.0.7** same code results expected result (string without need of force cast to string).

Some more debugging gave more informations, this piece causes unexpected results:
```
...
if($apc_key == 'http://xyz.com:terms:528') {
			file_put_contents(WP_CONTENT_DIR . '/debug.log', $apc_key . "\n", FILE_APPEND);
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($this->last_changed, true) . "\n", FILE_APPEND);
		}
		
		// $apc_key = "http://xyz.com:terms:528"
		$r = apcu_add($apc_key, $data, $expire);
		// $r = true
		
		if($apc_key == 'http://xyz.com:terms:528') {
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($r, true) . "\n", FILE_APPEND);
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($this->last_changed, true) . "\n", FILE_APPEND);
		}
...
```
first file_put_contents (before apcu_add() call) result:
```
Array
(
    [0] => Array
        (
            [terms] => 0.53625600 1453980591
        )
)
```
and second (after apcu_add() call):
```
Array
(
    [0] => Array
        (
            [terms] => O:8:"stdClass":10:{s:7:"term_id";i:528;s:4:"name";s:1:"a";s:4:"slug";s:6:"fghfgh";s:10:"term_group";i:0;s:16:"term_taxonomy_id";i:530;s:8:"taxonomy";s:13:"district_name";s:11:"description";s:0:"";s:6:"parent";i:0;s:5:"count";i:0;s:6:"filter";s:3:"raw";}
        )
)
```
and here's a simple example which reproduces this behaviour:
```
class Test {
	
	public $last_changed = array();
	
	public function add($key, $data, $group, $expire = 0) {
		$apc_key = "http://xyz.com.pl:$group:$key";
		
		return apcu_add($apc_key, $data, $expire);
	}
	
	public function set($key, $data, $group, $expire = 0) {
		$apc_key = "http://xyz.com.pl:$group:$key";

		if($key == 'last_changed') {
			$this->last_changed[] = array(
				$group => apcu_fetch($apc_key)
			);
		}

		if(apcu_store($apc_key, $data, $expire) !== false) {
			return true;
		}

		return false;
	}
	
}

$n = new Test();

$o = new stdClass();
$o->id = 100;

$n->set('last_changed', '0.82696300 1453987499', 'terms');

var_dump($n->last_changed);
/* array(1) {
  [0]=>
  array(1) {
    ["terms"]=>
    string(21) "0.82696300 1453987499"
  }
} */

$n->add(528, $o, 'terms');

var_dump($n->last_changed);
/* array(1) {
  [0]=>
  array(1) {
    ["terms"]=>
    string(34) "O:8:"stdClass":1:{s:2:"id";i:100;}"
  }
} */
```

If I'll use **Backward Compatibility extension** problem dissapears.

**Comment by szaqal83** [comment] 2016-01-28 11:42
Some more debugging gave more informations, this piece causes unexpected results:
```
...
if($apc_key == 'http://xyz.com:terms:528') {
			file_put_contents(WP_CONTENT_DIR . '/debug.log', $apc_key . "\n", FILE_APPEND);
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($this->last_changed, true) . "\n", FILE_APPEND);
		}
		
		// $apc_key = "http://xyz.com:terms:528"
		$r = apcu_add($apc_key, $data, $expire);
		// $r = true
		
		if($apc_key == 'http://xyz.com:terms:528') {
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($r, true) . "\n", FILE_APPEND);
			file_put_contents(WP_CONTENT_DIR . '/debug.log', print_r($this->last_changed, true) . "\n", FILE_APPEND);
		}
...
```
first file_put_contents result:
```
Array
(
    [0] => Array
        (
            [terms] => 0.53625600 1453980591
        )
)
```
and second (after apcu_add() call):
```
Array
(
    [0] => Array
        (
            [terms] => O:8:"stdClass":10:{s:7:"term_id";i:528;s:4:"name";s:1:"a";s:4:"slug";s:6:"fghfgh";s:10:"term_group";i:0;s:16:"term_taxonomy_id";i:530;s:8:"taxonomy";s:13:"district_name";s:11:"description";s:0:"";s:6:"parent";i:0;s:5:"count";i:0;s:6:"filter";s:3:"raw";}
        )
)
```

**Comment by omarkilani** [comment] 2016-02-05 21:15
FWIW, we have the same issue running 7.0.2 + apcu 5.1.3.

I've "solved" the problem by wrapping the APC calls like so:

```php
  function apc_store($key, $val, $ttl = 0) {
    return apcu_store($key, serialize($val), $ttl);
  }

  function apc_fetch($key) {
    $rv = apcu_fetch($key);
    if ($rv === false) {
      return false;
    }

    $rv = unserialize($rv);
    return $rv;
  }
```

**Comment by krakjoe** [comment] 2016-04-09 07:49
Sorry about the wait, super busy ...

I just today managed to reproduce this ... will investigate over the weekend ...

**Comment by bocharov** [comment] 2016-04-15 11:47
I'm confirming similar weird behaviour of APCu for PHP 7.0.5
When some big arrays get stored in APCu and then fetched - there is problem to access keys of those arrays (isset === false), but when printing value - it looks fine (key is present). Problem is when value of the key is array, not when simple string. Some corrupted memory problem I guess, but reproducing not all the time, floating bug, so cannot give simple reproducible case.

We solved this problem for us by changing setting apc.serializer from "default" to "php" and all mystery is gone after that.

**Comment by krakjoe** [comment] 2016-04-15 18:20
That reminds me of a bug we've seen before when the serializer wasn't set properly ... I'll have a review ...

**Comment by aaronbski** [comment] 2016-05-10 16:29
We're experiencing this strange behavior as well on PHP 7.0.6 and apcu "5.1.3+4.0.11." I found the initial test case a bit difficult to understand, so I tried to simplify it.

```
<?php

// In this test case, the Test class's property "prop" is set once from apc_fetch and
// should never change. But it does.

class Test
{
    public $prop;

    public function __construct($key)
    {
        $this->prop = apc_fetch($key);
    }

    public function set($key, $data)
    {
        apc_store($key, $data, 0);
    }
}

$key = 'prop';

apc_clear_cache('user');

var_dump(apc_fetch($key));
// boolean false

// Set a starting value
apc_add('prop', 'A', 0);

// Now $test->prop should always be 'A'
$test = new Test($key);

var_dump($test->prop);
// string 'A'

$test->set($key, 'B');

var_dump($test->prop);
// string 'A'

$test->set('unrelated key', 'C');

var_dump($test->prop);
// string 'C'
// Expected: string 'A'
```

**Comment by krakjoe** [comment] 2016-05-12 03:52
bump

**Comment by szaqal83** [comment] 2016-05-16 06:25
After upgrade to 5.1.4 problem still existed until I've removed:
```
apc.serializer = php
```
from module ini file. 

phpinfo() shows same value as before for apc.serializer which is "php" but module acts differently (doesn't produce weird behaviour now).

**Comment by eirikhm** [comment] 2016-05-30 14:11
Experiencing similar problems. Script to reproduce code:

`<?php

apcu_store('test', 'A');
$arrayFromApc = [apcu_fetch('test')];

echo "Diff non-APC\n";
echo var_export(array_diff(['A', 'B'], ['A']),true);

echo "\n\n";

echo "Diff APC:\n";
echo var_export(array_diff(['A', 'B'], $arrayFromApc),true);

`

**Comment by krakjoe** [comment] 2016-09-29 16:47
Can we try 5.1.6 please ?

I'm not able to reproduce any strangeness any more.

**Comment by szaqal83** [comment] 2016-10-06 09:37
On Debian Jessie 8.6 x64, PHP 7.0.11, APCu 5.1.5 (from dotdeb packages) works fine with or without
`apc.serializer=php`

**Comment by staabm** [comment] 2016-10-06 09:46
@szaqal83 did you just say that the underlying issue was fixed with at least APCu5.1.5?

**Comment by szaqal83** [comment] 2016-10-06 09:56
Yes, I can say that this issue doesn't appear anymore for me (PHP 7.0.11, APCu 5.1.5), didn't checked 5.1.6 yet because it isn't available in dotdeb packages for now.

**Comment by krakjoe** [comment] 2016-10-06 10:30
Excellent, thanks for feedback.

**Closed by krakjoe** 2016-10-06 10:30 UTC
Labels: bug
