### ISSUE TITLE
apcu_store locking is breaking down under high concurrency

### ISSUE THREAD

**Issue by LionsAd** [krakjoe/apcu#333] opened 2018-11-14 10:32 UTC
Something still is not quite right with apcu_store locking (5.1.11):

I saw up to 6 seconds for apcu_store() calls in production.

With my test script I can have it at least take 3.5 ms per call instead of 0.08 ms per call.

And _sometimes_ I can lock it after running high concurrency load (but happened just once and I did not get a trace).

With that script I can see that there are apcu_fetch / apcu_store sequences taking 300-445 ms per call -- which should never happen.

Test script is here:

```
<?php

$item = (object) [
  'data' => 'x',
];

for ($i = 0; $i < 1000; $i++) {
$cid = 'fabian:' . mt_rand(0,20);

$item = (object) [
  'created' => time(),
  'cid' => $cid,
  'data' => [
     'foo' => 'bar',
     'x' => $item->data,
  ],
];

$start = microtime(TRUE);

$old_item = apcu_fetch($cid);
apcu_store($cid, $item);

$diff = (microtime(TRUE) - $start) * 1000;

if ($diff > 10) {
  error_log(print_r([$diff], TRUE), 3, '/tmp/apcu.log');
}

echo $cid . PHP_EOL;
}
```

It only breaks down under high concurrency, with low concurrency the script takes 200 ms, with high concurrency, it takes up to 6 seconds and both _fetch and _store are slower then.

To test I used `ab -n10000 -c200 http://127.0.0.1/test.php`

Edit: The script is useless unfortunately as ab aborts the request once it sees the `echo` and the 1000 loop is too much data in the array. Trying to find a better example.

**Comment by nikic** [comment] 2018-11-14 19:55
I think that most likely what you're hitting here is not really an implementation bug, but just the fact that apcu has (essentially) a single global rwlock for the whole cache. Every read and write has to acquire a cache lock. While there can be multiple concurrent reads, writes are exclusive. If you have high concurrency and a write-heavy workload, there's going to be a lot of lock contention and some of the processes will have to wait (and potentially will be descheduled, while will drive up pause times by a lot).

The solution to this would be to introduce finer grained locking (or lock-free, but let's take this one step at a time...). The obvious way to do that would be to have a separate lock for each hashtable bucket, which would significantly reduce lock contention for the (hopefully common) case where accesses are distributed across hashtable buckets.

The other problem you may be hitting is that if SHM runs full, a store might trigger a full cache cleanup. This will lock the cache and then proceed to remove all entries, which may take a considerable amount of time.

**Comment by LionsAd** [comment] 2018-11-16 02:03
Thanks a lot for your reply!

I can confirm that SHM is not full [48 M / 256 M used, not too many keys], but the global write lock() problem is indeed what I am hitting.

However a finer lock won't help in my use case.

This is for Drupal 8 (and potentially Drupal 7):

Basically what happens is:

In Drupal 8 we use ACPu as a local "fast" backend combined with a "slow" backend like a database or redis via network.

We then have a cache backend called ChainedFast, which synchronizes both.

In theory we have three cache "bins" ("bootstrap", "discovery", "config"), which should not be written to, but be mostly read-only.

However on commerce sites this invariant is not true and there is write traffic going to those bins.

On a write the whole cache contents of that bin are deemed invalid by updating a timestamp.

After retrieval from the "slow" backend, they are then written to the fast backend.

And I presume that many clients are then trying to write the same values at the same time, which then piles up as the cache is faster invalidated than it can be re-written.

And once it starts to stampede things are already outdated again, etc.

Many of those "outdated" items are in reality still valid however, but as the backend operates by comparing the `created` timestamp of the data with the `bin invalidation timestamp`, it needs to write the whole item again.

I think `yac` (unless I misread the source code) has a check for if a value is written that is already present, which might help in my case, because many clients will try to write the same data -- as they all wait for the global write lock.

Another way would be to allow a write that just returns if the write lock is not free.
In fact that might even be one of the best ideas to use here.

Like an optimistic set.

Eventually the cache would be consistent again or it would fallback to the slow cache indefinitely if invalidations are too fast.

[And yes I also tried removing the bad invalidations, but there are still too many left. Also I am trying to find a generic solution.]

Another possibility in my application would be to store the `created` timestamp independent of the data item, which would allow me to save on `memcpy` at least, but I think I would still run into the global write lock, so an idea I had was to use `cas`, because as timestamps are strictly monolithic increasing the behavior I would need is:

```
$success = FALSE;

$old_value = get($key);
if ($old_value == $value) {
  acquire_write_lock();
  $old_value = get($key);
  if ($old_value == $value) {
    write($key, $new_value);
    $success = TRUE;
  }  
  release_write_lock();
}

return $success;
```

But I am not sure if `cas` is implemented in that way. Can you help me understand the implementation?

Thanks a lot!

**Comment by LionsAd** [comment] 2018-11-16 04:11
Okay, I see why apcu_store is pretty slow and why `cas` is 3x faster:

apcu_store() always needs to prepare, then remove the entry and then insert it new, which is a lot more effort than to just update the entry in place (if the size still kinda matches), which also explains why memcache uses slabs of data sizes to avoid this exact problem.

But it also means that my `cas` idea will work well with the current code -- because even if the value is not checked before the write lock is checked, I can check once myself before.

That would likely make performance 3x faster for the set() case.

**Comment by staabm** [comment] 2018-11-16 06:34
Couldnt you use some kind of stampede protection? E.g. Symfony added stampede protection for their cache component recently, see 
https://symfony.com/blog/new-in-symfony-4-2-cache-stampede-protection

**Comment by pbromb** [comment] 2018-11-16 09:04
I confirm this problem.
The problem is after the upgrade from 5.1.8 to 5.1.12
There are many entries in PHP slow log on function apcu_store
The problem is solved only by the PHP-FPM restart

In my project, cache apuc is used by doctrine-orm

**Comment by nikic** [comment] 2018-11-16 09:13
apcu is supposed to have some very primitive stampede protection (`apc.cache_slam` ini option, enabled by default). However, looking at the code I think it currently does not work, due to this check: https://github.com/krakjoe/apcu/blob/79af3692741025a3dcaa1b70c3c0a75042b53160/apc_cache.c#L1157 hash will be zero initially and due to the early exit here it's also going to stay zero forever...

**Comment by LionsAd** [comment] 2018-11-16 10:13
@nikic Ohhh, that is a good catch.

1. I also can confirm that poor performance of apcu_store() is also due to lock() performance. I switched it over to POSIX spin locks (btw. `--enable-apcu-spinlocks` is broken as it will not write the right entry to config.h) and most of the performance problems on apcu_store() got removed. (And yes I am aware that spinlocks do not sleep, but the futex is for most cases too slow). I suggest we could optionally implement the reader/writer algorithm used by POSIX with spinlocks. (https://locklessinc.com/articles/locks/)

2. I also thought about it and I think it would be better to use a lock per hash table entry instead of one global lock, which means `#locks == size_hint`. The reason is that even the function docs state that the hash table slot should be computed before taking any lock, so a global lock feels unnecessary.

3. Updating should not need a write lock, but only a read lock. However due to: current update function == delete + insert. => This makes it really slow for something, which should just atomically exchange the memory pointer for the item data.

4. I think lock-less reading could be possible as we just deal with a linked list per slot -- if carefully implemented [but that is larger risk].

5. Currently APCu depends on collisions a lot as 4096 is a pretty low key space for the hash function. It might be an idea to take some parts of the hash function of `yac` to make usage of linked lists less prominent and hence reduce collisions.

That would be all my ideas right now.

**Comment by LionsAd** [comment] 2018-11-16 10:36
Confirmed that fixing stampede protection at least for the `apcu_store` is making a real difference for the same key.

```
diff --git a/apc_cache.c b/apc_cache.c
index f4487f1..9b4b9f5 100644
--- a/apc_cache.c
+++ b/apc_cache.c
@@ -538,6 +538,22 @@ PHP_APCU_API zend_bool apc_cache_store(
        if (!ret) {
                apc_cache_destroy_context(&ctxt);
        }
+        else {
+               apc_cache_owner_t owner;
+#ifdef ZTS
+               owner = TSRMLS_CACHE;
+#else
+               owner = getpid();
+#endif
+
+               /* for copy of locking key struct */
+               apc_cache_slam_key_t *last = &cache->header->lastkey;
+               /* sets enough information for an educated guess, but is not exact */
+               last->hash = ZSTR_HASH(key);
+               last->len = ZSTR_LEN(key);
+               last->mtime = t;
+               last->owner = owner;
+        }
 
        return ret;
 } /* }}} */
```

**Comment by LionsAd** [comment] 2018-11-16 10:38
And likely that is one of the most important fixes, because especially that use case with removing the item, inserting again, then having the next process do the same can easily lock() things forever especially if a locked process is not scheduled for a while.

**Comment by LionsAd** [comment] 2018-11-16 11:33
Ohhh and I found the real culprit of `apcu_store` being so slow and spinlocks helping a lot to make it faster:

```
        /* initialize a context suitable for making an insert */
        if (!apc_cache_make_copy_in_context(cache, &ctxt, APC_SMALL_POOL)) {
                return 0;
        }
```

which calls `sma->sma_alloc()`, which uses a WLOCK, which locks everything.

Should not not be using a global POOL of APC_SMALL_POOL and then just allocate / deallocate from that pool?

It feels very wasteful to allocate / deallocate shared memory again and again ...

**Comment by nikic** [comment] 2018-11-16 19:18
@LionsAd Yeah, that code is already in master.

If you want to fix the stampede protection, rather than modifying the store function directly, I'd suggest a) drop the check in https://github.com/krakjoe/apcu/blob/master/apc_cache.c#L1157 and b) move https://github.com/krakjoe/apcu/blob/master/apc_cache.c#L1177 outside the both ifs. Turning that `result = 1` into an early return should make that simpler.

We should also have a test to make sure that this stays working... I think something based on fork should work. Maybe along these lines:

```php
$pid = pcntl_fork();
if ($pid) {
    // parent
    $ret1 = apcu_store("foo", "bar");
    pcntl_wait($pid);
    $ret2 = apcu_store("foo", "bar");
    if ($ret1 === false || $ret2 === false) {
        echo "Stampede protection works\n";
    } else {
        echo "Stampede protection doesn't work\n";
    }
} else {
    // child
    apcu_store("foo", "bar");
}
```

**Comment by nikic** [comment] 2018-11-17 21:13
I've opened a separate issue to track fine-grained locking in #337. Are there any other improvements that should be tracked?

**Comment by nikic** [comment] 2018-11-19 10:49
I'm closing this one in favor of the various other opened issues.

**Closed by nikic** 2018-11-19 10:49 UTC
