### ISSUE TITLE
APCu cache sharing

### ISSUE THREAD

**Issue by satboy78** [krakjoe/apcu#121] opened 2015-06-15 09:53 UTC
Hi,
on 'Php - The right way' I've read that

> when running PHP as a (Fast-)CGI application inside your webserver, every PHP process will have its own cache, i.e. APCu data is not shared between your worker processes.

But I know that the data cache is shared between all PHP child processes in php-fpm pool: can you please confirm that cache is shared?

Thanks a lot.

Best regards.

**Comment by theintz** [comment] 2015-08-20 13:07
I'd also be interested in the answer to this. My understanding of APC would also suggest that the entire pool of the php-fpm processes uses a single shared memory segment and thus shares the cache.
If this is correct, I would like to have an option to enable the other behavior, having isolated caches for each process in the pool. Is that possible?

**Comment by fruitl00p** [comment] 2015-08-20 13:11
@theintz I could answer that and that would be a PHP-FPM specific configuration: using multiple pools (i.e. http://www.if-not-true-then-false.com/2011/nginx-and-php-fpm-configuration-and-optimizing-tips-and-tricks/#php-fpm-pools-configuration) That way each pool could share their `own` APCu cache

**Comment by krakjoe** [comment] 2015-08-30 06:03
Just to answer the original question ... as @fruitl00p said, you can configure your way out of the problem of not being able to share if you are using fpm.

There is a difference between using fpm and using fcgi, I should probably put in a PR to phptherightway to clear it up.

The rule is that only child processes can access what their parent created; In FCGI spawned processes are not necessarily a child of their parent, they may not be actual forks. If your process manager works like conventional FCGI/CGI then you will not be able to share, if it works like FPM, and initializes PHP in a parent and forks child interpreters then you will have no problem.

Closing, because not a bug and you have your answers ;)

**Closed by krakjoe** 2015-08-30 06:03 UTC
